version: '3'
services:
  jupyterlab:
    image: jupyter/tensorflow-notebook:latest
    ports:
      - "8888:8888"
    volumes:
      - C:\Users\Yanay\Documents\GitHub\pv_forecast:/home/jovyan/work
    user: "0"